### ISSUE TITLE
Package organization

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-zarvis#17]
Your package organization could use some organization, in your `src`:

- [ ] Remove the tutorial files 

- [ ] Reorganize what you have in `main` and `zarvis` under a single folder. This may be the cause of some of your sonar issues and will cause issues later on with unit tests. (You should probably move everything, except the tests there)

- [ ] What is the out folder for? You have two places where the config is at the moment.

- [ ] Remove any temporary files that are not needed ~ 

See this: https://spring.io/guides/gs/gradle/

**Comment by ani3190** [comment]
package reorganized according to instructions.
