### ISSUE TITLE
Fix Broken Build... You've added an external dependency.

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-zarvis#3]
You've added an external dependency, and have not updated your project information.

Please be prepared to present your development workflow in the class tomorrow.

**Comment by moriarty** [comment]
<img width="1061" alt="screen shot 2017-11-20 at 22 21 50" src="https://user-images.githubusercontent.com/55676/33042334-c03479ac-ce41-11e7-97d6-bee4bf2b6c21.png">

**Comment by moriarty** [comment]
Travis, should not be used as "the tool" to test your compilation, you should only commit code which you've locally tested. You should not commit code which does not compile and does not pass travis to master, if a branch fails (why you should start #4 ), don't merge it.

Travis is a startup based in Berlin, and the offer the servers to Open Source projects for free, which is awesome. Please don't abuse it by not testing your code locally once.

<img width="1061" alt="screen shot 2017-11-23 at 22 50 45" src="https://user-images.githubusercontent.com/55676/33189213-f7906936-d0a0-11e7-8041-83e261d15fc7.png">

If it is compiling locally: then please clone it again and use the command line to compile, you've likely added something into your IDE.

**Comment by moriarty** [comment]
Fix the broken travis build on masters.

**Comment by moriarty** [comment]
@rubanraj54 @bouknify @ani3190 ?

**Comment by argenos** [comment]
I hope you have been able to fix and run gradle locally. 
Even if you haven't, you are probably aware that you are running the GUI and that your project never finishes.... That is what needs to be fixed by @bouknify 

![screenshot from 2017-12-10 12-53-56](https://user-images.githubusercontent.com/5426039/33804642-70844532-dda9-11e7-9d6c-ca6212969124.png)

**Comment by rubanraj54** [comment]
External dependencies added to the gradle file and code included in the main container to stop the main program after sometime(e.g 30 seconds).

**Comment by argenos** [comment]
@bouknify Travis is no longer executing `gradle run`, I'm assuming it got deleted on one of the merge requests trying to fix SonarQube

**Comment by ani3190** [comment]
The build seems to be fine to me now. Can you @argenos please confirm me after checking it? I can close this issue if it is okay..

**Comment by argenos** [comment]
@ani3190 in your Travis file, `gradle run` is missing after `gradle sonarqube`. Make that change and you can close both issues!
