### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-zarvis#4]
Please use the [git branching model](http://nvie.com/posts/a-successful-git-branching-model/), careful with your naming conventions

**Comment by moriarty** [comment]
@bouknify & @rubanraj54 & @ani3190:

Please start using standard branching workflow, and fix your currently failing travis build #3.

**Comment by argenos** [comment]
@rubanraj54 @bouknify  & @ani3190  you should really start using the git branching model instead of just committing to your master branch

**Comment by rubanraj54** [comment]
Yes, we discussed in our team about git branching model. Further commits in future will follow git branching model.

**Comment by moriarty** [comment]
Your master branch is still failing. Please open a topic branch, fix the build ASAP, and then merge the changes into master following the branching model.

Then, close this issue and #3.

**Comment by argenos** [comment]
@moriarty other things discussed today:

@ani3190 and @bouknify need to get their own forks. 

All team members must push their work in progress to their forks, and keep open pull requests to show they are working on the mentioned issues

**Comment by bouknify** [comment]
we started working in branching model
