### ISSUE TITLE
Setup SonarCloud

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-zarvis#5]
Please setup SonarCloud integration.

The @HBRS-MAAS/pieceofcake has partially set this up already.
And we're asking all teams to do so, and to go further and also setup the GitHub Plugin

1. HBRS-MAAS/project-pieceofcake#6 <- Why use Sonar? Read here.
2. HBRS-MAAS/project-pieceofcake#7 <- What is the GitHub Plugin? Read here.
3. HBRS-MAAS/project-gabych#4 <- Why use the GitHub Plugin? Read here.

This issue I'm copying to all teams.

**Comment by argenos** [comment]
@ani3190 you should create a branch for setting this up, and remove the current setup in the Travis file from master until it's working

**Comment by argenos** [comment]
You’re closer! We can see your fork here already: 
https://sonarcloud.io/dashboard?id=project-zarvis%3Afeature%2Fintegrate_sonarcloud

Add the badge to the readme, change the organization and merge to master!

**Comment by argenos** [comment]
@ani3190 in addition to the quality gate badge, please add a coverage badge to your readme. See [here](https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/wiki/Measure-badges)

**Comment by argenos** [comment]
@ani3190 to be able to use gradlew, please read [this](https://spring.io/guides/gs/gradle/), more specifically the section.
>  Build your project with Gradle Wrapper

This is related to #17 as well

**Comment by argenos** [comment]
@ani3190 I’m almost sure your issue comes from the way you’re setting the token. I’ve set it up using the instructions given by sonarcloud directly, see result here https://sonarcloud.io/dashboard?id=zarvis

Any command that Travis is trying to run, you need to be able to run beforehand on your laptop.

**Comment by ani3190** [comment]
Finally, the sonar cloud is set. I have also added the quality and coverage badge to readme. Can I close the issue now?
